import schedule
import time
import subprocess
import logging
import os
import pytz
from datetime import datetime

# Ensure the logs directory exists
os.makedirs("logs", exist_ok=True)

# Set up logging
logging.basicConfig(
    filename="logs/scheduler.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

# Set your desired local time zone (e.g., America/New_York)
LOCAL_TIMEZONE = pytz.timezone("America/New_York")


def run_script(script):
    """Run the specified Python script."""
    try:
        print(f"Running script: {script}")
        logging.info(f"Running script: {script}")
        subprocess.run(["python", f"scripts/{script}"], check=True)
        print(f"Script {script} ran successfully.")
        logging.info(f"Script {script} ran successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error running script {script}: {e}")
        logging.error(f"Error running script {script}: {e}")
    except Exception as e:
        print(f"Unexpected error running script {script}: {e}")
        logging.error(f"Unexpected error running script {script}: {e}")


def run_at_local_time(day, hour, minute, script):
    """
    Schedule a task to run at a specific local time on a specific day.
    Converts the local time to UTC before scheduling.
    """
    now = datetime.now(LOCAL_TIMEZONE)
    schedule_time = LOCAL_TIMEZONE.localize(datetime(now.year, now.month, now.day, hour, minute))
    utc_time = schedule_time.astimezone(pytz.utc)
    utc_time_str = utc_time.strftime("%H:%M")
    logging.info(f"Scheduling {script} for {day} at local time {hour:02d}:{minute:02d} ({utc_time_str} UTC)")

    # Use the appropriate schedule function based on the day
    if day.lower() == "monday":
        schedule.every().monday.at(utc_time_str).do(run_script, script=script)
    elif day.lower() == "tuesday":
        schedule.every().tuesday.at(utc_time_str).do(run_script, script=script)
    elif day.lower() == "wednesday":
        schedule.every().wednesday.at(utc_time_str).do(run_script, script=script)
    elif day.lower() == "thursday":
        schedule.every().thursday.at(utc_time_str).do(run_script, script=script)
    elif day.lower() == "friday":
        schedule.every().friday.at(utc_time_str).do(run_script, script=script)
    elif day.lower() == "saturday":
        schedule.every().saturday.at(utc_time_str).do(run_script, script=script)
    elif day.lower() == "sunday":
        schedule.every().sunday.at(utc_time_str).do(run_script, script=script)


def schedule_tasks():
    """Schedule tasks for the week with time zone handling."""
    # Monday
    def schedule_monday_tasks():
        """Schedule tasks for Monday."""
        run_at_local_time("monday", 11, 0, "65fm.py")
        run_at_local_time("monday", 11, 15, "65sm.py")
        run_at_local_time("monday", 11, 30, "65fm.py")
        run_at_local_time("monday", 11, 45, "65sm.py")
        run_at_local_time("monday", 12, 0, "65fm.py")
        run_at_local_time("monday", 12, 15, "65sm.py")
        run_at_local_time("monday", 12, 30, "70fm.py")
        run_at_local_time("monday", 12, 45, "70sm.py")
        run_at_local_time("monday", 13, 0, "70fm.py")
        run_at_local_time("monday", 13, 15, "70sm.py")
        run_at_local_time("monday", 13, 30, "70fm.py")
        run_at_local_time("monday", 13, 45, "70sm.py")
        run_at_local_time("monday", 14, 0, "75fm.py")
        run_at_local_time("monday", 14, 15, "75sm.py")
        run_at_local_time("monday", 14, 30, "75fm.py")
        run_at_local_time("monday", 14, 45, "75sm.py")
        run_at_local_time("monday", 15, 0, "75fm.py")
        run_at_local_time("monday", 15, 15, "75sm.py")
        run_at_local_time("monday", 15, 30, "75fm.py")
        run_at_local_time("monday", 15, 45, "75sm.py")
        run_at_local_time("monday", 16, 0, "75fm.py")
        run_at_local_time("monday", 16, 15, "75sm.py")
        run_at_local_time("monday", 16, 30, "75fm.py")
        run_at_local_time("monday", 16, 45, "75sm.py")
        run_at_local_time("monday", 17, 0, "75fm.py")
        run_at_local_time("monday", 17, 15, "75sm.py")
        run_at_local_time("monday", 17, 30, "75fm.py")
        run_at_local_time("monday", 17, 45, "75sm.py")
        run_at_local_time("monday", 18, 0, "75fm.py")
        run_at_local_time("monday", 18, 15, "75sm.py")
        run_at_local_time("monday", 18, 30, "75fm.py")
        run_at_local_time("monday", 18, 45, "75sm.py")
        run_at_local_time("monday", 19, 0, "75fm.py")
        run_at_local_time("monday", 19, 15, "75sm.py")
        run_at_local_time("monday", 19, 30, "75fm.py")
        run_at_local_time("monday", 19, 45, "75sm.py")
        run_at_local_time("monday", 20, 0, "75fm.py")
        run_at_local_time("monday", 20, 15, "75sm.py")
        run_at_local_time("monday", 20, 30, "75fm.py")
        run_at_local_time("monday", 20, 45, "75fm.py")
        run_at_local_time("monday", 21, 0, "75sm.py")
        run_at_local_time("monday", 21, 30, "75sm.py")
        run_at_local_time("monday", 21, 45, "75sm.py")
        run_at_local_time("monday", 22, 0, "75sm.py")
        run_at_local_time("monday", 22, 30, "75sm.py")
        run_at_local_time("monday", 23, 0, "70fm.py")
        run_at_local_time("monday", 23, 30, "65sm.py")
        run_at_local_time("monday", 23, 59, "pause.py")

    # Tuesday
    def schedule_tuesday_tasks():
        """Schedule tasks for Tuesday."""
        run_at_local_time("tuesday", 11, 0, "65fm.py")
        run_at_local_time("tuesday", 11, 15, "65sm.py")
        run_at_local_time("tuesday", 11, 30, "65fm.py")
        run_at_local_time("tuesday", 11, 45, "65sm.py")
        run_at_local_time("tuesday", 12, 0, "65fm.py")
        run_at_local_time("tuesday", 12, 15, "65sm.py")
        run_at_local_time("tuesday", 12, 30, "65fm.py")
        run_at_local_time("tuesday", 12, 45, "65sm.py")
        run_at_local_time("tuesday", 13, 0, "65fm.py")
        run_at_local_time("tuesday", 13, 15, "65sm.py")
        run_at_local_time("tuesday", 13, 30, "65fm.py")
        run_at_local_time("tuesday", 13, 45, "65sm.py")
        run_at_local_time("tuesday", 14, 0, "65fm.py")
        run_at_local_time("tuesday", 14, 15, "65sm.py")
        run_at_local_time("tuesday", 14, 30, "70fm.py")
        run_at_local_time("tuesday", 14, 45, "70sm.py")
        run_at_local_time("tuesday", 15, 0, "70fm.py")
        run_at_local_time("tuesday", 15, 15, "70sm.py")
        run_at_local_time("tuesday", 15, 30, "70fm.py")
        run_at_local_time("tuesday", 15, 45, "70sm.py")
        run_at_local_time("tuesday", 16, 0, "75fm.py")
        run_at_local_time("tuesday", 16, 15, "75sm.py")
        run_at_local_time("tuesday", 16, 30, "75fm.py")
        run_at_local_time("tuesday", 16, 45, "75sm.py")
        run_at_local_time("tuesday", 17, 0, "75fm.py")
        run_at_local_time("tuesday", 17, 15, "75sm.py")
        run_at_local_time("tuesday", 17, 30, "75fm.py")
        run_at_local_time("tuesday", 17, 45, "75sm.py")
        run_at_local_time("tuesday", 18, 0, "75fm.py")
        run_at_local_time("tuesday", 18, 15, "75sm.py")
        run_at_local_time("tuesday", 18, 30, "75fm.py")
        run_at_local_time("tuesday", 18, 45, "75sm.py")
        run_at_local_time("tuesday", 19, 0, "75fm.py")
        run_at_local_time("tuesday", 19, 15, "75sm.py")
        run_at_local_time("tuesday", 19, 30, "75fm.py")
        run_at_local_time("tuesday", 19, 45, "75sm.py")
        run_at_local_time("tuesday", 20, 0, "75fm.py")
        run_at_local_time("tuesday", 20, 15, "75sm.py")
        run_at_local_time("tuesday", 20, 30, "75fm.py")
        run_at_local_time("tuesday", 20, 45, "75fm.py")
        run_at_local_time("tuesday", 21, 0, "75sm.py")
        run_at_local_time("tuesday", 21, 30, "75sm.py")
        run_at_local_time("tuesday", 21, 45, "75sm.py")
        run_at_local_time("tuesday", 22, 0, "75sm.py")
        run_at_local_time("tuesday", 22, 30, "75sm.py")
        run_at_local_time("tuesday", 23, 0, "70fm.py")
        run_at_local_time("tuesday", 23, 30, "65sm.py")
        run_at_local_time("tuesday", 23, 59, "pause.py")

    # Wednesday
    def schedule_wednesday_tasks():
        """Schedule tasks for Wednesday."""
        run_at_local_time("wednesday", 11, 0, "75fm.py")
        run_at_local_time("wednesday", 11, 15, "75sm.py")
        run_at_local_time("wednesday", 11, 30, "75fm.py")
        run_at_local_time("wednesday", 11, 45, "75sm.py")
        run_at_local_time("wednesday", 12, 0, "75fm.py")
        run_at_local_time("wednesday", 12, 15, "75sm.py")
        run_at_local_time("wednesday", 12, 30, "75fm.py")
        run_at_local_time("wednesday", 12, 45, "75sm.py")
        run_at_local_time("wednesday", 13, 0, "75fm.py")
        run_at_local_time("wednesday", 13, 15, "75sm.py")
        run_at_local_time("wednesday", 13, 30, "75fm.py")
        run_at_local_time("wednesday", 13, 45, "75sm.py")
        run_at_local_time("wednesday", 14, 0, "75fm.py")
        run_at_local_time("wednesday", 14, 15, "75sm.py")
        run_at_local_time("wednesday", 14, 30, "75fm.py")
        run_at_local_time("wednesday", 14, 45, "75sm.py")
        run_at_local_time("wednesday", 15, 0, "75fm.py")
        run_at_local_time("wednesday", 15, 15, "75sm.py")
        run_at_local_time("wednesday", 15, 30, "75fm.py")
        run_at_local_time("wednesday", 15, 45, "75sm.py")
        run_at_local_time("wednesday", 16, 0, "75fm.py")
        run_at_local_time("wednesday", 16, 15, "75sm.py")
        run_at_local_time("wednesday", 16, 30, "75fm.py")
        run_at_local_time("wednesday", 16, 45, "75sm.py")
        run_at_local_time("wednesday", 17, 0, "75fm.py")
        run_at_local_time("wednesday", 17, 15, "75sm.py")
        run_at_local_time("wednesday", 17, 30, "75fm.py")
        run_at_local_time("wednesday", 17, 45, "75sm.py")
        run_at_local_time("wednesday", 18, 0, "75fm.py")
        run_at_local_time("wednesday", 18, 15, "75sm.py")
        run_at_local_time("wednesday", 18, 30, "75fm.py")
        run_at_local_time("wednesday", 18, 45, "75sm.py")
        run_at_local_time("wednesday", 19, 0, "75fm.py")
        run_at_local_time("wednesday", 19, 15, "75sm.py")
        run_at_local_time("wednesday", 19, 30, "75fm.py")
        run_at_local_time("wednesday", 19, 45, "75sm.py")
        run_at_local_time("wednesday", 20, 0, "75fm.py")
        run_at_local_time("wednesday", 20, 15, "75sm.py")
        run_at_local_time("wednesday", 20, 30, "75fm.py")
        run_at_local_time("wednesday", 20, 45, "75fm.py")
        run_at_local_time("wednesday", 21, 0, "75sm.py")
        run_at_local_time("wednesday", 21, 30, "75sm.py")
        run_at_local_time("wednesday", 21, 45, "75sm.py")
        run_at_local_time("wednesday", 22, 0, "75sm.py")
        run_at_local_time("wednesday", 22, 30, "75sm.py")
        run_at_local_time("wednesday", 23, 0, "75fm.py")
        run_at_local_time("wednesday", 23, 30, "65sm.py")
        run_at_local_time("wednesday", 23, 59, "pause.py")

    # Thursday
    def schedule_thursday_tasks():
        """Schedule tasks for Thursday."""
        run_at_local_time("thursday", 11, 0, "75fm.py")
        run_at_local_time("thursday", 11, 15, "75sm.py")
        run_at_local_time("thursday", 11, 30, "75fm.py")
        run_at_local_time("thursday", 11, 45, "75sm.py")
        run_at_local_time("thursday", 12, 0, "75fm.py")
        run_at_local_time("thursday", 12, 15, "75sm.py")
        run_at_local_time("thursday", 12, 30, "75fm.py")
        run_at_local_time("thursday", 12, 45, "75sm.py")
        run_at_local_time("thursday", 13, 0, "75fm.py")
        run_at_local_time("thursday", 13, 15, "75sm.py")
        run_at_local_time("thursday", 13, 30, "75fm.py")
        run_at_local_time("thursday", 13, 45, "75sm.py")
        run_at_local_time("thursday", 14, 0, "75fm.py")
        run_at_local_time("thursday", 14, 15, "75sm.py")
        run_at_local_time("thursday", 14, 30, "75fm.py")
        run_at_local_time("thursday", 14, 45, "75sm.py")
        run_at_local_time("thursday", 15, 0, "75fm.py")
        run_at_local_time("thursday", 15, 15, "75sm.py")
        run_at_local_time("thursday", 15, 30, "75fm.py")
        run_at_local_time("thursday", 15, 45, "75sm.py")
        run_at_local_time("thursday", 16, 0, "75fm.py")
        run_at_local_time("thursday", 16, 15, "75sm.py")
        run_at_local_time("thursday", 16, 30, "75fm.py")
        run_at_local_time("thursday", 16, 45, "75sm.py")
        run_at_local_time("thursday", 17, 0, "75fm.py")
        run_at_local_time("thursday", 17, 15, "75sm.py")
        run_at_local_time("thursday", 17, 30, "75fm.py")
        run_at_local_time("thursday", 17, 45, "75sm.py")
        run_at_local_time("thursday", 18, 0, "75fm.py")
        run_at_local_time("thursday", 18, 15, "75sm.py")
        run_at_local_time("thursday", 18, 30, "75fm.py")
        run_at_local_time("thursday", 18, 45, "75sm.py")
        run_at_local_time("thursday", 19, 0, "75fm.py")
        run_at_local_time("thursday", 19, 15, "75sm.py")
        run_at_local_time("thursday", 19, 30, "75fm.py")
        run_at_local_time("thursday", 19, 45, "75sm.py")
        run_at_local_time("thursday", 20, 0, "75fm.py")
        run_at_local_time("thursday", 20, 15, "75sm.py")
        run_at_local_time("thursday", 20, 30, "75fm.py")
        run_at_local_time("thursday", 20, 45, "75fm.py")
        run_at_local_time("thursday", 21, 0, "85sm.py")
        run_at_local_time("thursday", 21, 30, "85sm.py")
        run_at_local_time("thursday", 21, 45, "85sm.py")
        run_at_local_time("thursday", 22, 0, "80sm.py")
        run_at_local_time("thursday", 22, 30, "80sm.py")
        run_at_local_time("thursday", 23, 0, "80fm.py")
        run_at_local_time("thursday", 23, 30, "80sm.py")
        run_at_local_time("friday", 0, 0, "70sm.py")
        run_at_local_time("friday", 0, 30, "65sm.py")
        run_at_local_time("friday", 1, 0, "pause.py")

    # Friday
    def schedule_friday_tasks():
        """Schedule tasks for Friday."""
        run_at_local_time("friday", 11, 0, "75fm.py")
        run_at_local_time("friday", 11, 15, "75sm.py")
        run_at_local_time("friday", 11, 30, "75fm.py")
        run_at_local_time("friday", 11, 45, "75sm.py")
        run_at_local_time("friday", 12, 0, "75fm.py")
        run_at_local_time("friday", 12, 15, "75sm.py")
        run_at_local_time("friday", 12, 30, "75fm.py")
        run_at_local_time("friday", 12, 45, "75sm.py")
        run_at_local_time("friday", 13, 0, "75fm.py")
        run_at_local_time("friday", 13, 15, "75sm.py")
        run_at_local_time("friday", 13, 30, "75fm.py")
        run_at_local_time("friday", 13, 45, "75sm.py")
        run_at_local_time("friday", 14, 0, "75fm.py")
        run_at_local_time("friday", 14, 15, "75sm.py")
        run_at_local_time("friday", 14, 30, "75fm.py")
        run_at_local_time("friday", 14, 45, "75sm.py")
        run_at_local_time("friday", 15, 0, "75fm.py")
        run_at_local_time("friday", 15, 15, "75sm.py")
        run_at_local_time("friday", 15, 30, "75fm.py")
        run_at_local_time("friday", 15, 45, "75sm.py")
        run_at_local_time("friday", 16, 0, "75fm.py")
        run_at_local_time("friday", 16, 15, "75sm.py")
        run_at_local_time("friday", 16, 30, "75fm.py")
        run_at_local_time("friday", 16, 45, "75sm.py")
        run_at_local_time("friday", 17, 0, "75fm.py")
        run_at_local_time("friday", 17, 15, "75sm.py")
        run_at_local_time("friday", 17, 30, "75fm.py")
        run_at_local_time("friday", 17, 45, "75sm.py")
        run_at_local_time("friday", 18, 0, "75fm.py")
        run_at_local_time("friday", 18, 15, "75sm.py")
        run_at_local_time("friday", 18, 30, "75fm.py")
        run_at_local_time("friday", 18, 45, "75sm.py")
        run_at_local_time("friday", 19, 0, "80fm.py")
        run_at_local_time("friday", 19, 15, "80sm.py")
        run_at_local_time("friday", 19, 30, "80fm.py")
        run_at_local_time("friday", 19, 45, "80sm.py")
        run_at_local_time("friday", 20, 0, "80fm.py")
        run_at_local_time("friday", 20, 15, "80sm.py")
        run_at_local_time("friday", 20, 30, "85fm.py")
        run_at_local_time("friday", 20, 45, "85fm.py")
        run_at_local_time("friday", 21, 0, "85sm.py")
        run_at_local_time("friday", 21, 30, "85sm.py")
        run_at_local_time("friday", 21, 45, "85sm.py")
        run_at_local_time("friday", 22, 0, "85sm.py")
        run_at_local_time("friday", 22, 30, "80sm.py")
        run_at_local_time("friday", 23, 0, "80fm.py")
        run_at_local_time("friday", 23, 30, "80sm.py")

    # Saturday
    def schedule_saturday_tasks():
        """Schedule tasks for Saturday."""
        run_at_local_time("saturday", 11, 0, "75fm.py")
        run_at_local_time("saturday", 11, 15, "75sm.py")
        run_at_local_time("saturday", 11, 30, "75fm.py")
        run_at_local_time("saturday", 11, 45, "75sm.py")
        run_at_local_time("saturday", 12, 0, "75fm.py")
        run_at_local_time("saturday", 12, 15, "75sm.py")
        run_at_local_time("saturday", 12, 30, "75fm.py")
        run_at_local_time("saturday", 12, 45, "75sm.py")
        run_at_local_time("saturday", 13, 0, "75fm.py")
        run_at_local_time("saturday", 13, 15, "75sm.py")
        run_at_local_time("saturday", 13, 30, "75fm.py")
        run_at_local_time("saturday", 13, 45, "75sm.py")
        run_at_local_time("saturday", 14, 0, "75fm.py")
        run_at_local_time("saturday", 14, 15, "75sm.py")
        run_at_local_time("saturday", 14, 30, "75fm.py")
        run_at_local_time("saturday", 14, 45, "75sm.py")
        run_at_local_time("saturday", 15, 0, "75fm.py")
        run_at_local_time("saturday", 15, 15, "75sm.py")
        run_at_local_time("saturday", 15, 30, "75fm.py")
        run_at_local_time("saturday", 15, 45, "75sm.py")
        run_at_local_time("saturday", 16, 0, "75fm.py")
        run_at_local_time("saturday", 16, 15, "75sm.py")
        run_at_local_time("saturday", 16, 30, "75fm.py")
        run_at_local_time("saturday", 16, 45, "75sm.py")
        run_at_local_time("saturday", 17, 0, "75fm.py")
        run_at_local_time("saturday", 17, 15, "75sm.py")
        run_at_local_time("saturday", 17, 30, "75fm.py")
        run_at_local_time("saturday", 17, 45, "75sm.py")
        run_at_local_time("saturday", 18, 0, "80fm.py")
        run_at_local_time("saturday", 18, 15, "80sm.py")
        run_at_local_time("saturday", 18, 30, "80fm.py")
        run_at_local_time("saturday", 18, 45, "80sm.py")
        run_at_local_time("saturday", 19, 0, "80fm.py")
        run_at_local_time("saturday", 19, 15, "85sm.py")
        run_at_local_time("saturday", 19, 30, "85fm.py")
        run_at_local_time("saturday", 19, 45, "85sm.py")
        run_at_local_time("saturday", 20, 0, "85fm.py")
        run_at_local_time("saturday", 20, 15, "85sm.py")
        run_at_local_time("saturday", 20, 30, "85fm.py")
        run_at_local_time("saturday", 20, 45, "85fm.py")
        run_at_local_time("saturday", 21, 0, "85sm.py")
        run_at_local_time("saturday", 21, 30, "85sm.py")
        run_at_local_time("saturday", 21, 45, "85sm.py")
        run_at_local_time("saturday", 22, 0, "85sm.py")
        run_at_local_time("saturday", 22, 30, "85sm.py")
        run_at_local_time("saturday", 23, 0, "85fm.py")
        run_at_local_time("saturday", 23, 30, "85sm.py")

    # Sunday
    def schedule_sunday_tasks():
        """Schedule tasks for Sunday."""
        run_at_local_time("sunday", 11, 0, "75fm.py")
        run_at_local_time("sunday", 11, 15, "75sm.py")
        run_at_local_time("sunday", 11, 30, "75fm.py")
        run_at_local_time("sunday", 11, 45, "75sm.py")
        run_at_local_time("sunday", 12, 0, "75fm.py")
        run_at_local_time("sunday", 12, 15, "75sm.py")
        run_at_local_time("sunday", 12, 30, "75fm.py")
        run_at_local_time("sunday", 12, 45, "75sm.py")
        run_at_local_time("sunday", 13, 0, "75fm.py")
        run_at_local_time("sunday", 13, 15, "75sm.py")
        run_at_local_time("sunday", 13, 30, "75fm.py")
        run_at_local_time("sunday", 13, 45, "75sm.py")
        run_at_local_time("sunday", 14, 0, "75fm.py")
        run_at_local_time("sunday", 14, 15, "75sm.py")
        run_at_local_time("sunday", 14, 30, "75fm.py")
        run_at_local_time("sunday", 14, 45, "75sm.py")
        run_at_local_time("sunday", 15, 0, "75fm.py")
        run_at_local_time("sunday", 15, 15, "75sm.py")
        run_at_local_time("sunday", 15, 30, "75fm.py")
        run_at_local_time("sunday", 15, 45, "75sm.py")
        run_at_local_time("sunday", 16, 0, "75fm.py")
        run_at_local_time("sunday", 16, 15, "75sm.py")
        run_at_local_time("sunday", 16, 30, "75fm.py")
        run_at_local_time("sunday", 16, 45, "75sm.py")
        run_at_local_time("sunday", 17, 0, "75fm.py")
        run_at_local_time("sunday", 17, 15, "75sm.py")
        run_at_local_time("sunday", 17, 30, "75fm.py")
        run_at_local_time("sunday", 17, 45, "75sm.py")
        run_at_local_time("sunday", 18, 0, "75fm.py")
        run_at_local_time("sunday", 18, 15, "75sm.py")
        run_at_local_time("sunday", 18, 30, "75fm.py")
        run_at_local_time("sunday", 18, 45, "75sm.py")
        run_at_local_time("sunday", 19, 0, "75fm.py")
        run_at_local_time("sunday", 19, 15, "80sm.py")
        run_at_local_time("sunday", 19, 30, "80fm.py")
        run_at_local_time("sunday", 19, 45, "80sm.py")
        run_at_local_time("sunday", 20, 0, "85fm.py")
        run_at_local_time("sunday", 20, 15, "85sm.py")
        run_at_local_time("sunday", 20, 30, "85fm.py")
        run_at_local_time("sunday", 20, 45, "85fm.py")
        run_at_local_time("sunday", 21, 0, "85sm.py")
        run_at_local_time("sunday", 21, 30, "80sm.py")
        run_at_local_time("sunday", 21, 45, "80sm.py")
        run_at_local_time("sunday", 22, 0, "80sm.py")
        run_at_local_time("sunday", 22, 30, "75sm.py")
        run_at_local_time("sunday", 23, 0, "70fm.py")
        run_at_local_time("sunday", 23, 30, "65sm.py")
        run_at_local_time("sunday", 0, 0, "pause.py")


# Call the scheduling function
schedule_tasks()

# Run the scheduler loop
while True:
    schedule.run_pending()
    time.sleep(1)